# Generated by Django 3.2.3 on 2021-08-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210805_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(default=25, max_length=20),
            preserve_default=False,
        ),
    ]
