# Generated by Django 3.2.6 on 2021-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_order',
            field=models.BooleanField(default=False),
        ),
    ]
